fix:OS-SWP-SUG-01
soroswap/core pull request #146
Opened 2024-01-17 18:26 UTC by joaquinsoza

Fixing audit review, issue OS-SWP-SUG-01 Checking if address are not equal

2024-01-19 20:04 UTC, esteblock requested changes
@joaquinsoza Please add an Error here, not a panic.
See src/error.rs.

2024-01-22 16:24 UTC, joaquinsoza commented
Issue: #124 
Article: [Missing Address Check in Pair Contract](https://github.com/soroswap/articles/blob/main/audit-review/PairAddressCheck.md)

2024-01-23 03:00 UTC, esteblock requested changes
Check the correct use of map_err

2024-01-23 03:00 UTC, esteblock commented on contracts/factory/src/lib.rs
I don't think that .map_err is correctly used here.
In my opinion, only the "?" should be fine,

2024-01-23 03:45 UTC, esteblock commented
This might work well.
Please check: https://github.com/soroswap/core/pull/146/commits/c34ef0a3fc7cf779fe3a8e80e6a4e63e94ef9932

2024-01-23 12:16 UTC, joaquinsoza commented on contracts/factory/src/lib.rs
Perfect, I had gone through a solution with "?" but I discarded it when I had to make many changes to the contract...

2024-01-23 14:33 UTC, merged